import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/app/components/LegalDocument";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How TertiaryGuide collects, uses, stores, and protects personal information.",
  alternates: { canonical: "/privacy" },
};

const sections: LegalSection[] = [
  { id: "overview", title: "Overview", content: <><p>This Privacy Policy explains how TertiaryGuide collects, uses, shares, and protects information when you use our website, applicant services, school portals, communications, and related products.</p><p>By using TertiaryGuide, you acknowledge the practices described here. We process personal information responsibly and with regard to applicable Ghanaian data protection requirements, including the Data Protection Act, 2012 (Act 843).</p></> },
  { id: "information", title: "Information we collect", content: <><p>Depending on the service you use, we may collect:</p><ul><li><strong>Account information:</strong> name, username, email address, phone number, password hash, profile image, and account preferences.</li><li><strong>Application information:</strong> personal and guardian details, education history, examination information, programme choices, nationality, address, and other information required by a school.</li><li><strong>Documents:</strong> passport photographs, result slips, birth certificates, national identification documents, transcripts, and other files you choose or are required to upload.</li><li><strong>Transaction information:</strong> order details, payment references, amounts, purchased forms or checker vouchers, and fulfilment status. Payment card details are handled by Paystack and are not stored by TertiaryGuide.</li><li><strong>Technical and usage information:</strong> browser and device information, IP address, page activity, timestamps, referral information, and a locally stored visitor identifier.</li><li><strong>Communications:</strong> support requests, comments, marketing preferences, email interactions, and messages exchanged with us or participating schools.</li></ul></> },
  { id: "use", title: "How we use information", content: <ul><li>Create and secure your account.</li><li>Process form, voucher, checker, and application purchases.</li><li>Prepare, submit, manage, and communicate about school applications.</li><li>Deliver receipts, credentials, status updates, reminders, and requested support.</li><li>Show relevant schools, programmes, deadlines, content, and advertising.</li><li>Operate school and administrator portals, prevent misuse, and maintain audit records.</li><li>Understand performance and improve the reliability and usability of our services.</li><li>Comply with legal obligations and enforce our agreements.</li></ul> },
  { id: "sharing", title: "How information is shared", content: <><p>We do not sell personal information. We may share information with:</p><ul><li><strong>Schools and institutions</strong> when necessary to provide application or admissions services you request.</li><li><strong>Service providers</strong> supporting hosting, databases, file storage, analytics, email delivery, and security, including Vercel, MongoDB, Cloudinary, and Resend.</li><li><strong>Paystack</strong> to initiate, verify, and administer payments.</li><li><strong>Authorities or professional advisers</strong> where required by law, necessary to protect rights and safety, or needed to investigate fraud or misuse.</li><li><strong>A successor organization</strong> in connection with a merger, acquisition, financing, or transfer of the service, subject to appropriate safeguards.</li></ul></> },
  { id: "storage", title: "Storage and retention", content: <><p>Information may be processed or stored using service providers operating in Ghana or other countries. We retain information for as long as needed to provide the service, meet institutional and financial record requirements, resolve disputes, prevent fraud, and comply with law.</p><p>Retention periods vary by record type. Application and transaction records may need to be retained longer than general account or marketing information. When information is no longer required, we take reasonable steps to delete, anonymize, or securely isolate it.</p></> },
  { id: "security", title: "Security", content: <p>We use reasonable administrative, technical, and organizational measures to protect information, including access controls, password hashing, restricted administrative tools, and secure third-party infrastructure. No online system can guarantee absolute security, so users should protect their credentials and promptly report suspected unauthorized access.</p> },
  { id: "cookies", title: "Cookies and local storage", content: <p>TertiaryGuide uses browser storage and similar technologies to maintain sign-in state, remember preferences, support purchases and notifications, prevent duplicate actions, and understand site usage. You can clear browser storage through your browser settings, although doing so may sign you out or remove saved preferences.</p> },
  { id: "choices", title: "Your rights and choices", content: <><p>Subject to applicable law, you may request access to, correction of, or deletion of your personal information, object to certain processing, or withdraw consent where processing relies on consent.</p><p>You can manage notification preferences through your dashboard. Marketing messages may also include a preference link. Essential account, payment, security, and application communications may still be sent when necessary to provide the service.</p></> },
  { id: "children", title: "Children and applicants", content: <p>Some applicants may be under 18. Where legally required, a parent, guardian, or authorized school representative should assist with the submission of personal information. Users must not submit another person&apos;s information without appropriate authority.</p> },
  { id: "changes", title: "Changes to this policy", content: <p>We may update this policy as our services, providers, or legal obligations change. The revised policy will be posted on this page with an updated effective date. Material changes may also be communicated through the website or by email.</p> },
  { id: "contact", title: "Contact us", content: <p>For privacy questions or requests, contact TertiaryGuide at <a href="mailto:info@tertiaryguide.com">info@tertiaryguide.com</a>, call <a href="tel:+233595110767">+233 59 511 0767</a> or <a href="tel:+233248967314">+233 24 896 7314</a>, or write to us at Ho, Trafalgar, Ghana.</p> },
];

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" description="This policy explains what information we collect, why we use it, and the choices available to you when using TertiaryGuide." updated="7 September 2026" sections={sections} />;
}
