import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/app/components/LegalDocument";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing access to and use of TertiaryGuide services.",
  alternates: { canonical: "/terms" },
};

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement to these terms", content: <p>These Terms of Service govern your access to TertiaryGuide, including our website, school and applicant portals, programme information, application services, university forms, WASSCE checker products, payments, content, and communications. By using the service, you agree to these terms and our Privacy Policy.</p> },
  { id: "eligibility", title: "Eligibility and accounts", content: <><p>You must provide accurate information and have legal authority to use the information and documents you submit. Applicants under 18 should use the service with the involvement of a parent or guardian where required.</p><p>You are responsible for keeping account credentials, voucher codes, serial numbers, PINs, and application access information confidential. Notify us promptly if you suspect unauthorized access.</p></> },
  { id: "services", title: "Our services", content: <><p>TertiaryGuide helps users discover programmes and institutions, monitor deadlines, purchase forms and checker vouchers, submit applications to participating schools, and receive related support.</p><p>Availability, requirements, prices, deadlines, programme details, and admission decisions may be supplied or controlled by schools and other third parties. We work to keep information accurate, but users should verify important requirements with the relevant institution.</p></> },
  { id: "applications", title: "Applications and admissions", content: <ul><li>You are responsible for reviewing application information and documents before submission.</li><li>Submitting an application does not guarantee admission, placement, funding, or a response by a particular date.</li><li>Admissions decisions are made by the relevant institution, not TertiaryGuide.</li><li>A school may request additional documents, fees, interviews, corrections, or verification.</li><li>False, misleading, incomplete, or unauthorized submissions may be rejected or reported to the relevant institution.</li></ul> },
  { id: "payments", title: "Payments, vouchers, and refunds", content: <><p>Payments are processed through Paystack or another displayed payment provider. You authorize the applicable charges when confirming a transaction. Prices and any service fees are shown before payment.</p><p>Digital vouchers, checker credentials, application access codes, and fulfilled services may not be refundable once issued, revealed, used, submitted, or transmitted to you, except where required by law or where TertiaryGuide confirms a fulfilment failure. Duplicate or incorrect payments should be reported promptly with the payment reference.</p><p>Do not resell, publish, share, manipulate, or fraudulently obtain voucher codes, serial numbers, PINs, or payment confirmations.</p></> },
  { id: "communications", title: "Communications", content: <p>You agree that we may send service communications relating to account verification, security, purchases, fulfilment, deadlines, applications, support, and material service changes. Optional marketing messages can be managed through available preference controls.</p> },
  { id: "conduct", title: "Acceptable use", content: <><p>You must not:</p><ul><li>Use the service for fraud, impersonation, unlawful activity, or unauthorized data collection.</li><li>Upload malware, harmful code, unlawful content, or documents you have no right to use.</li><li>Interfere with the service, bypass access controls, probe security, or overload our systems.</li><li>Scrape, copy, resell, or commercially exploit the service without written permission.</li><li>Misrepresent affiliation with TertiaryGuide or a participating institution.</li></ul></> },
  { id: "content", title: "Content and intellectual property", content: <><p>TertiaryGuide and its licensors retain rights in the platform, branding, design, software, editorial content, and compiled data. School names, logos, and materials may belong to their respective institutions.</p><p>You retain ownership of information and documents you submit. You grant TertiaryGuide a limited right to host, process, reproduce, and transmit them only as needed to provide, secure, and improve the requested services.</p></> },
  { id: "third-parties", title: "Third-party services", content: <p>The service may link to or integrate with schools, payment providers, social networks, storage providers, and other third parties. Their services are governed by their own terms and policies. TertiaryGuide is not responsible for third-party systems or content outside our reasonable control.</p> },
  { id: "availability", title: "Availability and changes", content: <p>We may update, suspend, restrict, or discontinue parts of the service for maintenance, security, legal, institutional, or operational reasons. We do not guarantee uninterrupted availability, particularly where interruptions result from networks, institutions, payment providers, hosting services, or events beyond our control.</p> },
  { id: "disclaimers", title: "Disclaimers and liability", content: <><p>The service is provided on an &quot;as available&quot; basis. To the extent permitted by law, TertiaryGuide disclaims implied warranties that are not expressly stated in these terms.</p><p>TertiaryGuide is not responsible for admission decisions, changes made by institutions, missed deadlines caused by inaccurate third-party information, or indirect and consequential losses. Nothing in these terms excludes liability that cannot legally be excluded.</p></> },
  { id: "suspension", title: "Suspension and termination", content: <p>We may restrict or terminate access where we reasonably believe an account is involved in fraud, security threats, unlawful conduct, serious policy violations, or harm to users, institutions, or the service. You may stop using the service at any time and may request account deletion subject to necessary legal and operational retention.</p> },
  { id: "law", title: "Governing law", content: <p>These terms are governed by the laws of the Republic of Ghana. The parties should first attempt to resolve disputes in good faith. Where a dispute cannot be resolved informally, it may be submitted to the courts or another competent dispute-resolution forum in Ghana.</p> },
  { id: "changes", title: "Changes to these terms", content: <p>We may revise these terms to reflect changes to our services, institutions, providers, or legal obligations. Updated terms will be posted here with a revised date. Continued use after the effective date means you accept the revised terms.</p> },
  { id: "contact", title: "Contact us", content: <p>Questions about these terms can be sent to <a href="mailto:info@tertiaryguide.com">info@tertiaryguide.com</a>. You may also call <a href="tel:+233595110767">+233 59 511 0767</a> or <a href="tel:+233248967314">+233 24 896 7314</a>, or contact us at Ho, Trafalgar, Ghana.</p> },
];

export default function TermsPage() {
  return <LegalDocument title="Terms of Service" description="These terms set out the rules, responsibilities, and protections that apply when you use TertiaryGuide." updated="7 September 2026" sections={sections} />;
}
